spin_manifest_version = 2

[application]
name = "spinkube-documentation"
version = "0.1.0"
description = "The SpinKube documentation website running on Spin."
authors = ["SpinKube Maintainers"]

[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-fileserver"
component = "fileserver"
route = "/..."

[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "public/", destination = "/" }]

[component.fileserver.build]
command = "npm run build"
watch = ["content/**/*", "assets/**/*", "layouts/**/*"]
